#!/bin/sh
# LatentForge one-line installer.
#
#   curl -fsSL https://raw.githubusercontent.com/nazuraki/LatentForge/main/install.sh | sh
#
# Pulls the published image and starts the stack with Docker Compose. No
# configuration needed — on first visit the web UI walks through setup.
# Re-running is safe: it pulls the latest image and restarts.
#
# Prompts for the install directory (default ~/latentforge, or LATENTFORGE_HOME)
# and whether to include the containerized GPU worker (sticky across re-runs;
# non-interactive runs can opt in with LATENTFORGE_WORKER=1). Non-interactive
# runs use defaults without prompting.

set -eu

IMAGE="ghcr.io/nazuraki/latentforge:latest"
WORKER_IMAGE="ghcr.io/nazuraki/latentforge-worker:latest"
DIR_DEFAULT="${LATENTFORGE_HOME:-$HOME/latentforge}"
PORT="${LATENTFORGE_PORT:-19526}"

fail() {
  echo "error: $1" >&2
  exit 1
}

command -v docker >/dev/null 2>&1 || fail "Docker is required — install it from https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required (the 'docker compose' plugin)"
docker info >/dev/null 2>&1 || fail "the Docker daemon isn't running (or you lack permission to talk to it)"

# Under `curl | sh` stdin is the script, so prompts must use the terminal
# directly. No terminal (CI, automation) = take defaults silently.
# test -r/-w only checks permission bits; actually opening /dev/tty is what
# fails when there is no controlling terminal.
HAVE_TTY=0
if { : < /dev/tty; } 2>/dev/null; then
  HAVE_TTY=1
fi

DIR="$DIR_DEFAULT"
if [ "$HAVE_TTY" = "1" ]; then
  printf 'Install directory [%s]: ' "$DIR_DEFAULT" > /dev/tty
  IFS= read -r reply < /dev/tty || reply=""
  case "$reply" in
    "") ;;
    "~") DIR="$HOME" ;;
    "~/"*) DIR="$HOME/${reply#\~/}" ;;
    *) DIR="$reply" ;;
  esac
fi
mkdir -p "$DIR"

# Update-or-append KEY=value in $DIR/.env (compose reads it automatically).
set_env() {
  f="$DIR/.env"
  touch "$f" && chmod 600 "$f"
  if grep -q "^$1=" "$f" 2>/dev/null; then
    tmp="$f.tmp.$$"
    grep -v "^$1=" "$f" > "$tmp" || true
    printf '%s=%s\n' "$1" "$2" >> "$tmp"
    mv "$tmp" "$f"
  else
    printf '%s=%s\n' "$1" "$2" >> "$f"
  fi
}

# Worker opt-in. Once enabled it sticks (COMPOSE_PROFILES=worker in .env), so
# re-running the installer updates both images without re-asking.
WORKER=0
if grep -q '^COMPOSE_PROFILES=.*worker' "$DIR/.env" 2>/dev/null; then
  WORKER=1
elif [ "${LATENTFORGE_WORKER:-0}" = "1" ]; then
  WORKER=1
elif [ "$HAVE_TTY" = "1" ]; then
  printf 'Include the GPU worker container? Needs an NVIDIA GPU + nvidia-container-toolkit. [y/N]: ' > /dev/tty
  IFS= read -r reply < /dev/tty || reply=""
  case "$reply" in
    [Yy]*) WORKER=1 ;;
  esac
fi

if [ "$WORKER" = "1" ]; then
  docker info 2>/dev/null | grep -qi 'Runtimes:.*nvidia' \
    || echo "warning: NVIDIA runtime not detected in Docker — install nvidia-container-toolkit or the worker won't start" >&2

  # The worker authenticates with the shared token. The backend stores it in
  # the data volume where the worker container can't read it, so it must be in
  # .env: taken from LATENTFORGE_WORKER_TOKEN, else ~/.latentforge/token (a
  # previous host-side worker install), else prompted.
  if ! grep -q '^LATENTFORGE_WORKER_TOKEN=.' "$DIR/.env" 2>/dev/null; then
    TOKEN="${LATENTFORGE_WORKER_TOKEN:-}"
    if [ -z "$TOKEN" ] && [ -f "$HOME/.latentforge/token" ]; then
      TOKEN="$(cat "$HOME/.latentforge/token")"
      echo "Using the worker token from ~/.latentforge/token."
    fi
    if [ -z "$TOKEN" ] && [ "$HAVE_TTY" = "1" ]; then
      printf 'Worker token (shown in the UI under Settings after first-run setup): ' > /dev/tty
      IFS= read -r TOKEN < /dev/tty || TOKEN=""
    fi
    [ -n "$TOKEN" ] || fail "the worker needs the shared token: set LATENTFORGE_WORKER_TOKEN, or finish first-run setup in the UI and re-run"
    set_env LATENTFORGE_WORKER_TOKEN "$TOKEN"
  fi
  set_env COMPOSE_PROFILES worker
fi

cat > "$DIR/docker-compose.yml" <<EOF
# Generated by the LatentForge installer — re-running the installer overwrites
# this file. Put customizations in docker-compose.override.yml instead.
services:
  latentforge:
    image: $IMAGE
    ports:
      - "$PORT:19526"
    environment:
      LATENTFORGE_WORKER_TOKEN: \${LATENTFORGE_WORKER_TOKEN:-}
    volumes:
      - latentforge-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:19526/api/health').then(r=>process.exit(r.ok?0:1),()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

  # GPU worker — dormant unless COMPOSE_PROFILES=worker (set by the installer
  # when you opt in). Checkpoints come from ~/.latentforge/models on the host.
  worker:
    image: $WORKER_IMAGE
    profiles: ["worker"]
    hostname: "\${LATENTFORGE_WORKER_NAME:-latentforge-gpu}"
    environment:
      LATENTFORGE_BACKEND_URL: http://latentforge:19526
      LATENTFORGE_WORKER_TOKEN: \${LATENTFORGE_WORKER_TOKEN:-}
    volumes:
      - "\${LATENTFORGE_MODELS_DIR:-~/.latentforge/models}:/models:ro"
      - worker-hf-cache:/cache/huggingface
    depends_on:
      latentforge:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  latentforge-data:
  worker-hf-cache:
EOF

cd "$DIR"
docker compose pull
docker compose up -d

echo
echo "LatentForge is running."
echo
echo "  Open http://localhost:$PORT to finish setup in your browser."
echo "  (First visit walks you through creating the worker token.)"
if [ "$WORKER" = "1" ]; then
  echo
  echo "  GPU worker enabled — checkpoints are read from ~/.latentforge/models"
  echo "  (override with LATENTFORGE_MODELS_DIR in $DIR/.env)."
fi
echo
echo "  Installed in: $DIR"
echo "  Stop with:    docker compose -f $DIR/docker-compose.yml down"
