#!/bin/sh
# LatentForge one-line installer.
#
#   curl -fsSL https://raw.githubusercontent.com/nazuraki/LatentForge/main/install.sh | sh
#
# Pulls the published image and starts the stack with Docker Compose. No
# configuration needed — on first visit the web UI walks through setup.
# Re-running is safe: it pulls the latest image and restarts.
#
# Prompts for the install directory (default ~/latentforge, or LATENTFORGE_HOME);
# non-interactive runs use the default without prompting.

set -eu

IMAGE="ghcr.io/nazuraki/latentforge:latest"
DIR_DEFAULT="${LATENTFORGE_HOME:-$HOME/latentforge}"
PORT="${LATENTFORGE_PORT:-19526}"

fail() {
  echo "error: $1" >&2
  exit 1
}

command -v docker >/dev/null 2>&1 || fail "Docker is required — install it from https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required (the 'docker compose' plugin)"
docker info >/dev/null 2>&1 || fail "the Docker daemon isn't running (or you lack permission to talk to it)"

# Under `curl | sh` stdin is the script, so the prompt must use the terminal
# directly. No terminal (CI, automation) = take the default silently.
DIR="$DIR_DEFAULT"
# test -r/-w only checks permission bits; actually opening /dev/tty is what
# fails when there is no controlling terminal.
if { : < /dev/tty; } 2>/dev/null; then
  printf 'Install directory [%s]: ' "$DIR_DEFAULT" > /dev/tty
  IFS= read -r reply < /dev/tty || reply=""
  case "$reply" in
    "") ;;
    "~") DIR="$HOME" ;;
    "~/"*) DIR="$HOME/${reply#\~/}" ;;
    *) DIR="$reply" ;;
  esac
fi

mkdir -p "$DIR"
cat > "$DIR/docker-compose.yml" <<EOF
# Generated by the LatentForge installer — re-running the installer overwrites
# this file. Put customizations in docker-compose.override.yml instead.
services:
  latentforge:
    image: $IMAGE
    ports:
      - "$PORT:19526"
    volumes:
      - latentforge-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:19526/api/health').then(r=>process.exit(r.ok?0:1),()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

volumes:
  latentforge-data:
EOF

cd "$DIR"
docker compose pull
docker compose up -d

echo
echo "LatentForge is running."
echo
echo "  Open http://localhost:$PORT to finish setup in your browser."
echo "  (First visit walks you through creating the worker token.)"
echo
echo "  Installed in: $DIR"
echo "  Stop with:    docker compose -f $DIR/docker-compose.yml down"
